map:
  size: [20, 20]             # in meters
  x_min: 0
  x_max: 20
  y_min: 0
  y_max: 20
  resolution: 0.05           # meters per cell
  prob_occ: 0.9              # probability of occupancy for hits
  prob_free: 0.1
  prob_unknown: 0.5          
  log_odds_min: -10.0         # minimum log-odds
  log_odds_max: 10.0          # maximum log-odds
  origin: [0, 0]           # meters offset for map center


plot:
  plot_output_filename: "output/final_map.png"
  liveplot_speed: 0.1
  robot_color: "blue"
  lidar_color: "red"
  lidar_alpha: 0.3
  show_trail: False           # whether to show robot path
  trail_length: 100          # number of poses to show

ros:
  scan_topic: "/scan"
  odom_topic: "/odom"
  rate: 100                   # processing rate in Hz
  rosbag_path: "/mnt/c/Users/Pedro Coelho/Desktop/SAut_local/Novo_4/RoundTripSlow_17_junho.bag"