map:
  size: [20, 20]             # in meters
  x_min: 0
  x_max: 20
  y_min: 0
  y_max: 20
  resolution: 0.05           # meters per cell
  prob_occ: 0.7             # probability of occupancy for hits
  prob_free: 0.3
  prob_unknown: 0.5          
  log_odds_min: -10.0         # minimum log-odds
  log_odds_max: 10.0          # maximum log-odds
  origin: [0, 0]           # meters offset for map center


plot:
  liveplot_speed: 0.1
  robot_color: "blue"
  lidar_color: "red"
  lidar_alpha: 0.3

  rate: 10                   # processing rate in Hz
  